# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

#去掉由pod引入的第三方库的警告, 需要使用更新命令才生效
inhibit_all_warnings!

target 'picViewer' do
	pod 'YYKit'
    #Github排名第一的网络操作框架,底层是用NSURLSession+NSOperation(多线程)
    pod 'AFNetworking'
    #对系统Sqlite的封装,使用SQL语句操作数据库
    pod 'FMDB'
    #把系统的target+selector/委托模式 转为 Block语法,让代码结构更加紧凑
    pod 'BlocksKit'
    #对系统原生的AutoLayout的NSLayoutConstraints类的封装,优雅的链式语法,Github排名第三
    pod 'Masonry'
    #对CFNetwork操作Socket通讯的封装, 变为易懂好用的OC语法
    pod 'CocoaAsyncSocket'
    #侧边栏--参考QQ的侧边栏
    pod 'RESideMenu'
    #在屏幕中间显示忙 -- 小菊花, 类似于安卓的toast效果
    pod 'MBProgressHUD'
    #为滚动控件(UIScrollView,UITableView,UICollectionView)添加头部和脚部刷新UI
    pod 'MJRefresh'
    #对NSLog进行的封装,效率比NSLog高,大量打印不卡顿,可以分级打印
    pod 'CocoaLumberjack'
end

target 'picViewerTests' do

end

target 'picViewerUITests' do

end

