# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'picViewer' do
	pod 'YYKit'
end

target 'picViewerTests' do

end

target 'picViewerUITests' do

end

